language: python
python:
- '3.4'
install:
- pip install -r requirements-test.txt
script:
- tox
env:
  matrix:
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py33-django16
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django16
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  global:
  # PROXY_HOST_URL
  - secure: cVeSsiEmk0El0GEV3BXTM2vLy5FRI+LgnRIRM3UbFud968qFenkE+FlmoD/4ZxQCeMup66NMyyv91jKeupQ3gKfdFmzUlKAiD0Ok37B965L57hxiFZnVXopTGzWUQ/0BsPpjd/O37mEqSEBGclRPjeFL73+Z/GnZYBvo+byrUJr5KHPm8QThT9LotvsosBcpuvAZ06IExFTVYZbbbeRn8FJ8ZJkN5RmOLwrS2HANDH0hPUbC2vUVrbMRvoDserErCHAMgFASgPn5e1+VW9G1w8Nm70zG/3/oweDNHH7I3MSAoMo3T5IJD6vWfDU+0lsee2QeLNs/kzUPYR0Bl6rr4yUIwDJwhY/NgT62ZZA4kjjN2ycEZkwlxdvtUUWUCdSe6hzMW6jPt4V2/Hk6E4rkBKJQ6cSJmXICG9ROmDux7RR6x9u4/S6aDDtPXO2qI4G9pAEwvbmLw3ZIab7a/21DqkWYzDpj9izYuJmz1vpPuoeuR+LzpEkSbSfzgtHX6GJOX+2/bEMcb5uza1aFeZHQqBRI6TY4Wg7vGWi6BpSpKlhEzaQ1+vtsiVbKkLFFCn6gd9sFFne5yeMV84GwsgppEhQkH3dAGMo8XmYIgSwd62HGiA/nCtnmCN96GApvRJIG+g5b8hbNgih+xa3M37iLkU1tJP91K4lqChfAqWknXlw=
  - TEST_CERTIFICATE_PATH=test_cert.pfx
  - TEST_CERTIFICATE_PERSON_CODE=00000000000
  - TEST_CERTIFICATE_PASSWORD=test
deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      LWOCnrLw1BrrWGrZdsZ6Zfo7scQCZhfmR23vujUCgi7PZE1fODI3HJ/L6fz7uuzD2SBgi8Ihqg4xxOkskhD+OIp6mKjUySPOlVxMqp/Z8jSOk
      Z3tKKml9froW1OCAsDDPb09h5Z4BsBjY+5lGPUpvg2pbd9sDbRWr/i1HydV8kkwmynP7f/d3tpp8FDKLlPLJY5Afo/AqoG5BtUi26IgY0IrE8
      5tVa9KSZx1aCq9sFMxP35bM6CMuIn1SXtw7K349iaIu3ly1+qPDbQWjaDW4Ba1TzE2SPsi2ldBwV2pxMY0lubIagvnlWpg6v+HM+IqC8fTw4f
      aeK8du3JeckxjQXvjrCRymlEXBL/QNELIpGWP7wy/wxsoAZa5e+5xHMP4Ri7hANcfQsEGo+OKTisf+1Ft8w2RIKrNTxL0Rp1DCA2T7njWossH
      pyKEpmfQdk0WIs3ykthtCwew8QpFm6v4VaW29Z9H+rx2S3OdF59hL90iuxlTRBV93TO2KdH5RIbgR65fvx8COc+BBJycvl/ck3cU5zaWA5dJp
      UEu0phOld41Vejlu/ulKRmAI9EdrL5e+8Scbe2kXNXDM9C/7Uldo/ZBrq3JcV5EyYdoLZZAF0NRo93L0C8tSpJOZuVilNldDhzYgQ6ALeSez0
      7Gp4RtN+2KKLCJPvIiMgbLN9T8+nM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: thorgate/python-lvis
before_install:
- openssl aes-256-cbc -K $encrypted_dd19fa13e5b8_key -iv $encrypted_dd19fa13e5b8_iv
  -in test_cert.pfx.enc -out test_cert.pfx -d
