language: python

python:
- '3.4'

install:
- pip install -r requirements-test.txt

script:
- tox

env:
  matrix:
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py33-django16
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django16
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  global:
  # PROXY_HOST_URL
  - secure: epoVlAowo5qnpGpF/OpHp/Dtrw2F0gT5QKKNBuMlVw4+lDfH1OZf2iBDEneuqKt8GEftCaId2H8YU6dKLilnOFTj0LaXCJJNFdKlha6L0yU1WbVmNPBFmu7ug2XVHL2jQrVGGAn1JNtMzn1NxFBZCo43+Lxxnlw9YmsSZPfF4CLdaR9CawLIYtqjb0fHwO971j6qzosivgBxSOBL7K8ybg6M/TG9r+fiHxUPybGI1Cl6Nr/13Y+GGN0i8a1MRJo+xO4maPOejlhlMJvyUI4XofLsh7rqFTL5ve7JxKGkUZzoPKQJFLNIf11jD3MB5XrHBmu7AX/mTbLDgC9E5lRnSWGXcfi4RhrU+SeQfE3kzqGEGyf5YHvxV2GWVFSREDYm/1fy3M47kCwaopVcWO03LJGU8RinrU8yrmCHb85LWX+8EmTafqnXKnQ7xiyj4oSXIHdv6EtTUdg1144Oxph6X8wDmTCh+siNB3LKYpI88DkIl3gEo+heOoHffcG5oGcThWrpJ5WllpyPGbe1sI7cG2o+i7rpz5hAueJraBAS5HGVqUzEr6gh/UQhPIRjvXI2RLAT1JZ2L9VWVS6d7VXBJd2k0D9I4bezebnDETDQpo+fZsVZC2f5q33ZXAMquNVNVIjiXNEm1rZt2me+zEpKdoGydoQM26ZHIeub1m55DGo=
  - TEST_CERTIFICATE_PATH=test_cert.pfx
  - TEST_CERTIFICATE_PERSON_CODE=00000000000
  - TEST_CERTIFICATE_PASSWORD=test

deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      XB//mP+/76Xhhr0QEbws7ygvdUMHbiaA3Et/XRGkYycUOKGHqvheiORpuS7Wzs1kdvvoilRjFdnJ0y4LFigWbr8vBtb1WIvf87Tp9W1xepnPo
      qKtkVbTcTWcwrX4HA1kDXWhUG3yZIBT9zlQX2c3JBM40YfF+rDCAvdigaczjSqaZW7E5kUvoXu0XdrNT7ly1Qf4qEt2IYzgrAAeMEPkKWYgzY
      kjr+a0iXiY4QwPcU2wzCxOPUuRDgU78GIQ9SRjHs3UHrrnAwXfQw/4ajahvM56kuAUa7IJtSkAGdidZ6rFQLmKCloEOhKRiAKNAg2IUCNhtVu
      /HXSC+0DqirrHG+nxRFOK+u7BAxhcObGJ04CZe1icbZx1kpPlN6Vlxo/QT4iO1t/CRpZvF/UQBBJ4Q4w0MPEE3YEnRq0MhF3XtZe4slP0JIwV
      7Rzi92835NpNJc6pn6sOAge4kZsaoNfBCdIKLulZrFjmRhOn7PMzgPqWC6ueAcO/ZW5Ib4FIgLlx+Z7/UweRjD4OaVtyaPlERtr2efYUmbfOR
      Pyd7Sdq0HlOtM+fQ22W/wdSTA90ZcWjtATXMc84tHRWAyxCt8EhDRkbMU53SJ3UA427Riy5fC2KAv9OQiBDVMCD1AsMg9ZrlH0jeIjxUEXYFm
      EwmeXbr3RPFIKx47c+21jTof+L120=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: thorgate/python-lvis

before_install:
- openssl aes-256-cbc -K $encrypted_dd19fa13e5b8_key -iv $encrypted_dd19fa13e5b8_iv
  -in test_cert.pfx.enc -out test_cert.pfx -d

notifications:
    email: false
