language: python

python:
- '3.4'

install:
- pip install -r requirements-test.txt

script:
- tox

env:
  matrix:
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py33-django16
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django16
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  global:
  # PROXY_HOST_URL
  - secure: epoVlAowo5qnpGpF/OpHp/Dtrw2F0gT5QKKNBuMlVw4+lDfH1OZf2iBDEneuqKt8GEftCaId2H8YU6dKLilnOFTj0LaXCJJNFdKlha6L0yU1WbVmNPBFmu7ug2XVHL2jQrVGGAn1JNtMzn1NxFBZCo43+Lxxnlw9YmsSZPfF4CLdaR9CawLIYtqjb0fHwO971j6qzosivgBxSOBL7K8ybg6M/TG9r+fiHxUPybGI1Cl6Nr/13Y+GGN0i8a1MRJo+xO4maPOejlhlMJvyUI4XofLsh7rqFTL5ve7JxKGkUZzoPKQJFLNIf11jD3MB5XrHBmu7AX/mTbLDgC9E5lRnSWGXcfi4RhrU+SeQfE3kzqGEGyf5YHvxV2GWVFSREDYm/1fy3M47kCwaopVcWO03LJGU8RinrU8yrmCHb85LWX+8EmTafqnXKnQ7xiyj4oSXIHdv6EtTUdg1144Oxph6X8wDmTCh+siNB3LKYpI88DkIl3gEo+heOoHffcG5oGcThWrpJ5WllpyPGbe1sI7cG2o+i7rpz5hAueJraBAS5HGVqUzEr6gh/UQhPIRjvXI2RLAT1JZ2L9VWVS6d7VXBJd2k0D9I4bezebnDETDQpo+fZsVZC2f5q33ZXAMquNVNVIjiXNEm1rZt2me+zEpKdoGydoQM26ZHIeub1m55DGo=
  - TEST_CERTIFICATE_PATH=test_cert.pfx
  - TEST_CERTIFICATE_PERSON_CODE=00000000000
  - TEST_CERTIFICATE_PASSWORD=test

jobs:
  include:
    - stage: deploy
      env: TOXENV=py34-django18
      deploy:
        provider: pypi
        user: thorgate
        password:
          secure: >
            KRZ4RNRXcpX3VCAnM4csLPHOTXF/RtpuwfaaCyz6//502mPKuT1i/RnpMcER6Mnyilv0uuNpCONxciwqzUG/m8sJ2R64lv2pwVoNUqcvWfynh
            PaGfcTZKSqAKTcsi1Mv2UHACS5BJfaGqPYW2LWRRKZxxEeyq04gkJ/2hKPc3tvCXfSWOOFCThBJbxmd5l/KzGsawdEZptnVvck+fvPAHCkaAu
            qpfCjuZCTZGt5bS5L0ibvOIr8fgDVsDTkG+uAm4iVQDTJZUWkrAIRj53Fzlt1vbYhFTXGb9noW0dtzBoAg5CvStCudpFdZWDVcMWy14BuRHmS
            SSeAB3xnbEyrlFAyEic+HgiqGyiLXsvNlKSgzpOeppq+2p2YWLQaMbvcmFMDWwD8kdD5yubcE8Mjq9uoBtMxuc8kKsdArgoTbGvQU45sfyKCd
            gIfG98sWsZpx7O1M8r0TNvSpJcHu5v0II9kBrapTg3ZSPpVA+aDA22YF4IX/Y1NNy2/AmwbxsIuJI6JYu3JVo8JPaHtICZQtPBML7ZKvcxwXa
            MWxuTNfge4185I68psnnoO6JjVUjk5aY2VGETQ1p+pFA22jn7KTTX4+mO3t8nyLwWKJfkr6h4uf5DyxymqaUAZUj14yfnKWJ//9cqolb/LFzG
            SmZfkBvtvj7snZNw9O7GrcF6Y9WI0=
        on:
          tags: true
          distributions: sdist bdist_wheel
          repo: thorgate/python-lvis

before_install:
- openssl aes-256-cbc -K $encrypted_dd19fa13e5b8_key -iv $encrypted_dd19fa13e5b8_iv
  -in test_cert.pfx.enc -out test_cert.pfx -d

notifications:
    email: false
